
name: Deploy to Github pages

on:
 push:
  branches: [main]
 workflow_dispatch:
permissions:
 contents: read
 pages: write
 id-token: write

concurrency:
 group: pages
 cancel-in-progress: false

jobs:
 build: 
  runs-on: ubuntu-latest
  steps:
   - name: Checkout Repo
     uses: actions/checkout@v4
    #  with:
      # fetch-depth: 0
   - uses: pnpm/action-setup@v3
     with:
      version: 8.15.2
   - name: Setup Node
     uses: actions/setup-node@v4
     with:
      node-version: 20
      cache: pnpm
   - name: setup pages
     uses: actions/configure-pages@v4
   - name: Instal dependencies
     run: pnpm install
   - name: Build Shit
     run: pnpm docs:build
   - name: Upload Artifact
     uses: actions/upload-pages-artifact@v3
     with:
      path: docs/.vitepress/dist

 deploy:
  environment:
   name: Github pages
   url: ${{steps.deployment.outputs.page_url}}
  needs: build
  runs-on: ubuntu-latest
  name: Deploy
  steps:
   - name: Deploy to Github Pages
     id: deploymeny
     uses: actions/deploy-pages@v4




